### ISSUE TITLE
Make testAudit an actual test

### ISSUE THREAD

**Issue by philipjackson** [gliff-ai/annotate#163] opened 2021-05-27 16:19 UTC
**Is your feature request related to a problem? Please describe.**

`testAudit` is currently a method in the `Annotations` class, which is pretty weird. Should really be an automated test. 

**Describe the solution you'd like**

Would be cool to write a test that calls `Annotations` methods at random and then runs `testAudit`, that way we'll eventually catch all the weird edge cases.

**Comment by ChasNelson1990** [comment] 2022-01-06 12:36
duplicate of gliff-ai/audit#49

**Closed by ChasNelson1990** 2022-01-06 12:36 UTC
Labels: test
